name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v2
    
  #   - name: Build the docker_compose
  #     run: docker-compose up -d --build
      
  #   - name: Buid the application
  #     run: docker-compose exec -T counter_app npm run build

  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
            RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY  }}
            EC2_SSH_USERNAME : ${{ secrets.EC2_SSH_USERNAME  }}
            EC2_SSH_PUBLIC_IP_ADDRESS : ${{ secrets.EC2_SSH_PUBLIC_IP_ADDRESS  }}
        run: |
          echo "$RSA_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${EC2_SSH_USERNAME}@${EC2_SSH_PUBLIC_IP_ADDRESS} '
            echo " " &&

            echo "**Command: navigating to directory cd /var/www/html --------------------" &&
            cd /var/www/html && echo " " && echo " " &&

            echo "**Command: checkout main -----------------------------------------------" &&
            sudo git checkout main && echo " " && echo " " &&

            echo "**Command: git fetch ---------------------------------------------------" &&
            sudo git fetch --all && echo " " && echo " " &&

            echo "**Command: git reset ---------------------------------------------------" &&
            sudo git reset --hard origin/main && echo " " && echo " " &&
            
            echo "**Command: git pull ----------------------------------------------------" &&
            sudo git pull origin main && echo " " && echo " " &&
            
            echo "**Command: npm install --omit=dev --------------------------------------" &&
            sudo npm install --omit=dev && echo " " && echo " " &&
            
            echo "**Command: composer install -o --no-dev --------------------------------" &&
            sudo composer install -o --no-dev
          '