name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit tests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
            RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY  }}
            EC2_SSH_USERNAME : ${{ secrets.EC2_SSH_USERNAME  }}
            EC2_SSH_PUBLIC_IP_ADDRESS : ${{ secrets.EC2_SSH_PUBLIC_IP_ADDRESS  }}
        run: |
          echo "$RSA_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${EC2_SSH_USERNAME}@${EC2_SSH_PUBLIC_IP_ADDRESS} '
            echo && \

            echo "**Command: navigating to directory cd /var/www/html --------------------" &&
            cd /var/www/html && echo -e "\n" &&

            echo "**Command: checkout main -----------------------------------------------" &&
            sudo git checkout main && echo -e "\n" &&

            echo "**Command: git fetch ---------------------------------------------------" &&
            sudo git fetch --all && echo -e "\n" &&

            echo "**Command: git reset ---------------------------------------------------" &&
            sudo git reset --hard origin/main && echo -e "\n" &&
            
            echo "**Command: git pull ----------------------------------------------------" &&
            sudo git pull origin main && echo -e "\n" &&
            
            echo "**Command: npm install --omit=dev --------------------------------------" &&
            sudo npm install --omit=dev && echo -e "\n" &&
            
            echo "**Command: composer install -o --no-dev --------------------------------" &&
            sudo composer install -o --no-dev
          '