name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v2
    
  #   - name: Build the docker_compose
  #     run: docker-compose up -d --build
      
  #   - name: Buid the application
  #     run: docker-compose exec -T counter_app npm run build

  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy in EC2
        env:
            RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY  }}
            EC2_SSH_USERNAME : ${{ secrets.EC2_SSH_USERNAME  }}
            EC2_SSH_PUBLIC_IP_ADDRESS : ${{ secrets.EC2_SSH_PUBLIC_IP_ADDRESS  }}
        run: |
          echo "$RSA_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${EC2_SSH_USERNAME}@${EC2_SSH_PUBLIC_IP_ADDRESS} '
          
            echo "**navigating to directory" &&
            cd /var/www/html &&

            echo "**checkout main" &&
            sudo git checkout main &&

            echo "**git fetch" &&
            sudo git fetch --all &&

            echo "**git reset" &&
            sudo git reset --hard origin/main &&
            
            echo "**git pull" &&
            sudo git pull origin main
          '